### ISSUE TITLE
Not an issue - playback capabilities - did you ever get the json frames to playback the robot? 

### ISSUE THREAD

**Issue by johndpope** [laanlabs/ARBodyPoseRecorder#1]
I'm in realitykit land and have been capturing arframes in a (failed) attempt to play these back. 
I used a different approach to save the data 
https://gist.github.com/8secz-johndpope/1ba5920a6af75936b4e6a534899d1bea
I didn't check if my data contains camera view. 

scenekit seems to favour the playback more so - because we can unravel the robot from the arbody detection. I need to dig further into your code. If you have any sample to load the save reocording to animate the robot - I would be indebted.

**Comment by johndpope** [comment]
got it working. I'm curious why all the json frames are needed? perhaps my solution may suffice
https://github.com/8secz-johndpope/ARBodyPoseRecorder

**Comment by cclaan** [comment]
We are using this for offline analysis in python, so playback on device wasn't needed. Glad you got it working. But to playback all you'd need to do is set the transform of each joint again along with the root transform https://github.com/laanlabs/ARBodyPoseRecorder/blob/master/ARBodyPoseRecorder/ViewController.swift#L368
